@startuml
'https://plantuml.com/sequence-diagram
!include style.puml
hide circle
skinparam classAttributeIconSize 0
Class Ui {
+ greetings()
+ setLineBreak()
+ printHelpMessage()
+ printMaxNumberMessage()
+ printDeletingTooManyBooksMessage(numberInInventory, quantityToDelete, bookTitle)
+ printDeleteStatement(quantity, bookTitle, numberInventory, numberTotal)
+ exitProgramme()
+ printUserBooks(user, userCount, listOfUsers)
}

note right
There are more methods inside Ui, including
exceptions message. However for simplicity,
these details are omitted.
end note
@enduml